-- AlterTable
ALTER TABLE "Alert" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "triggered" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "userId" INTEGER,
ALTER COLUMN "triggeredAt" DROP NOT NULL,
ALTER COLUMN "triggeredAt" DROP DEFAULT;
